### ISSUE TITLE
Bad Gateway - https://try.gitea.io/

### ISSUE THREAD

**Issue by ritiek** [go-gitea/website#58] opened 2017-12-11 08:26 UTC
I stumbled across https://gitea.io/en-US/ but when I tap "Try Gitea", it responses with `Bad Gateway`.

**Comment by lafriks** [comment] 2017-12-11 09:19
go-gitea/gitea#3147 fixes this, as soon as this is merged try gitea should be working again

**Comment by lafriks** [comment] 2017-12-11 10:09
Fixed

**Closed as completed by lafriks** 2017-12-11 10:09 UTC
Labels: priority/critical

**Comment by ritiek** [comment] 2017-12-11 10:11
Thanks! I can confirm it works now.

**Comment by Adrian-Voelker** [comment] 2018-03-07 13:48
Hello, 
the issue is back. 
When I open "https://try.gitea.io/", response is "Bad Gateway" again.

**Comment by hliebel** [comment] 2018-03-19 13:22
Hi.
Broken for me too.
> Unable to connect
> Firefox can’t establish a connection to the server at try.gitea.io.
