### ISSUE TITLE
https://try.gitea.io/ is down?

### ISSUE THREAD

**Issue by treedust** [go-gitea/website#65] opened 2018-03-20 20:18 UTC
![cantbereached](https://user-images.githubusercontent.com/16553346/37680435-7eda38b4-2c49-11e8-9d2c-759eef14f460.png)

Is something I came across when looking at gitea.io

**Comment by lafriks** [comment] 2018-03-20 21:35
It is know, try.gitea.io is being moved to larger DO instance because of regular issues with disk space

**Comment by treedust** [comment] 2018-03-20 21:57
Thank you.

**Comment by strk** [comment] 2018-03-22 19:56
Duplicate of #58

**Comment by bkcsoft** [comment] 2018-04-28 22:01
It's up :)

**Closed as completed by bkcsoft** 2018-04-28 22:01 UTC
